# Generated by Django 5.1.3 on 2024-11-15 19:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelingApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sport', models.CharField(blank=True, max_length=255, null=True)),
                ('planned_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration in Minutes')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.PositiveIntegerField(blank=True, null=True, verbose_name='Water (ml)')),
                ('sodium', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='Sodium (mg)')),
                ('carbs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Carbohydrates')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fueling_plan', to='FuelingApp.workout')),
            ],
        ),
        migrations.CreateModel(
            name='CyclingWorkoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity_factor', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('tss', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Training Stress Score')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_details', to='FuelingApp.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration in Minutes')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_log', to='FuelingApp.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutFuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.PositiveIntegerField(blank=True, null=True, verbose_name='Water (ml)')),
                ('sodium', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='Sodium (mg)')),
                ('carbs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Carbohydrates')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('workout_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_fuel_log', to='FuelingApp.workoutlog')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_condition', models.CharField(blank=True, choices=[('Cold', 'Cold'), ('Cool', 'Cool'), ('Warm', 'Warm'), ('Hot', 'Hot'), ('Very Hot', 'Very Hot')], max_length=255, null=True, verbose_name='Perceived Weather Condition')),
                ('isIndoors', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('workout_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_condition', to='FuelingApp.workoutlog')),
            ],
        ),
        migrations.CreateModel(
            name='FuelingIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloating_gi', models.PositiveIntegerField(blank=True, choices=[(0, 'None'), (5, 'Some'), (10, 'Severe')], null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Bloating (GI)')),
                ('cramping', models.PositiveIntegerField(blank=True, choices=[(0, 'None'), (5, 'Some'), (10, 'Severe')], null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Cramping')),
                ('bonking', models.PositiveIntegerField(blank=True, choices=[(0, 'None'), (5, 'Some'), (10, 'Severe')], null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Bonking')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('workout_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fueling_issues', to='FuelingApp.workoutlog')),
            ],
        ),
        migrations.CreateModel(
            name='CyclingWorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity_factor', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('tss', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Training Stress Score')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('workout_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycling_workout_log', to='FuelingApp.workoutlog')),
            ],
        ),
    ]
