# Generated by Django 5.1.3 on 2024-11-16 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelingApp', '0002_workout_fuelingplan_cyclingworkoutdetails_workoutlog_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuelingIssues',
            new_name='FuelingIssue',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='tss',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Training Stress Score'),
        ),
        migrations.AlterField(
            model_name='workoutcondition',
            name='isIndoors',
            field=models.BooleanField(default=False, verbose_name='IsIndoors?'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
