# Generated by Django 5.1.3 on 2024-11-16 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelingApp', '0003_rename_fuelingissues_fuelingissue_workoutlog_tss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='intensity_factor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='workout',
            name='tss',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Training Stress Score'),
        ),
        migrations.AlterField(
            model_name='fuelingplan',
            name='carbs',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='fuelingplan',
            name='sodium',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Sodium (mg)'),
        ),
        migrations.AlterField(
            model_name='fuelingplan',
            name='water',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Water (ml)'),
        ),
        migrations.AlterField(
            model_name='workoutcondition',
            name='weather_condition',
            field=models.CharField(blank=True, choices=[('cold', 'Cold'), ('cool', 'Cool'), ('warm', 'Warm'), ('hot', 'Hot'), ('very_hot', 'Very Hot')], max_length=255, null=True, verbose_name='Perceived Weather Condition'),
        ),
        migrations.AlterField(
            model_name='workoutfuellog',
            name='carbs',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='workoutfuellog',
            name='sodium',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Sodium (mg)'),
        ),
        migrations.AlterField(
            model_name='workoutfuellog',
            name='water',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Water (ml)'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='calories',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
