# Generated by Django 5.1.3 on 2024-11-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelingApp', '0004_workout_intensity_factor_workout_tss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
