# Generated by Django 5.1.3 on 2024-11-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelingApp', '0005_alter_workout_planned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='sport',
            field=models.CharField(blank=True, choices=[('cycling', 'Cycling'), ('mountain_biking', 'Mountain Biking'), ('running', 'Running'), ('xc_skiing', 'XC Skiing')], max_length=255, null=True),
        ),
    ]
