# Generated by Django 5.1.3 on 2024-11-20 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuelingApp', '0006_alter_workout_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
