# Generated by Django 5.1.3 on 2024-11-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_userprofile_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='metrics_unit',
            field=models.BooleanField(default=True, verbose_name='Metric Unit?'),
        ),
    ]
