# Generated by Django 5.1.3 on 2024-11-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_userprofile_metrics_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='metrics_unit',
            field=models.BooleanField(default=True, verbose_name='Metric Unit?'),
        ),
    ]
